### ISSUE TITLE
Website Specification

### ISSUE THREAD

**Issue by didehvar** [didehvar/monarchy-node#1]
Every single blasted feature needs to be on display in this fine document. All of the sites screens and flows need to be well documented as to allow rapid development. In parenthesis next to most headings is an example of what the URL should look like on each page (a heading roughly represents a page).
# Navigation
- [ ] Site logo - links to homepage
- [ ] Forums - links to discourse
- [ ] Sign up / Log in
- [ ] If signed in display a private message indicator, links to the forum private messages
# Homepage (/)
## Left section (60% of page?)
- [ ] News taken live from Discourse
  - [ ] Header/title
  - [ ] User that posted (icon for admins? like on Discourse?)
  - [ ] Date posted (minimum day, month? what about year or time? or even x hours/days ago?)
  - [ ] Full news post or extract? Perhaps the first paragraph (allows people to summarize news post)?
  - [ ] "Read more" or "Continue the discussion" link? Show how many replies?
## Right section (40% of page?)
- [ ] Latest tournaments
  - [ ] Title
  - [ ] Season
  - [ ] What game the tournament is for? (maybe like Dota 2 - University League or CS:GO - Champions League?)
  - [ ] Area for sponsors? Maybe small logos?
  - [ ] How many teams have registered/are participating? (is this important enough?)
  - [ ] Whether you can register/when registration ends?
  - [ ] Type of tournament? (probably not important enough for front page?)
  - [ ] Upcoming matches (if the tournament has started), perhaps the next two or three?
- [ ] Streams
  - [ ] Online streams
  - [ ] Upcoming streams
  - [ ] Should link to the match page when upcoming, if live should auto-link to the embedded stream page
# Accounts (/users)
## Account Implementation (/users/me)
- [ ] Support Discourse SSO
- [ ] Allow steam sign in
- [ ] Account fields/properties, all fields should be editable (\* required on sign up) (+ private)
  - [ ] Username *(not required for steam sign in)
    - [ ] Min 3 characters, max 20
  - [ ] Email \* +
  - [ ] Password *(not required for steam sign in) +
    - [ ] Min 8 characters
  - [ ] Steam id (auto set with steam sign in)
  - [ ] Avatar (auto set with steam sign in)
  - [ ] University email (required for uni only tournaments) +
  - [ ] Staff (null, mod, admin)
    - [ ] Extra staff email
    - [ ] Role/position, should sso to lowercase'd title if possible (might not be)
- [ ] Extra fields
  - [ ] Skype username
  - [ ] Twitch channel name
- [ ] Account options
  - [ ] Update any of the above fields
  - [ ] Delete account (should this fire a Discourse delete?)
## User Pages (/users/username)
- [ ] Display public fields
- [ ] Teams currently in
- [ ] Tournaments currently participating in
- [ ] Tournaments previously participated in (show rank/position)

Extra information displayed for users marked as staff
- [ ] Staff email
- [ ] Role/position in team

Changes for users marked as casters
- [ ] Tournaments currently casting
- [ ] Online indicator (just a green dot next to the twitch link or something?)
- [ ] Embed caster live stream if online?
- [ ] Comments/feedback section, anyone logged in can comment, uses a Discourse thread created for a user when they are first marked as a caster in the casters category
# Tournaments (/tournaments/title-slug)

Each tournament should have its own page which shows all stored tournament details, as listed below.
- [ ] Title
- [ ] Season
- [ ] Sponsors
- [ ] Game
  - [ ] This should define how many players are in a team
- [ ] Type (single/double elim/robin)
- [ ] Various start and end dates for
  - [ ] Registrations
  - [ ] Qualifiers(if there is qualifiers?)
  - [ ] Main tournament (brackets)
- [ ] Cap on teams that can register
- [ ] Admins for this tournament
- [ ] University only tournament
- [ ] On this page users should be able to click a 'sign up' button which should trigger various responses:
  - If the user is not a member of a team: (Only teams can enter this tournament. (link)Would you like to create a team?)
  - If the user is a member of a team but not a captain:(Only team captains can sign teams up for competitions.)
  - If the user is a captain of a team that is incomplete: (Only complete teams can sign up for this tournament. You currently only have x/y members in (link)your team.)
  - If the user is a captain of a full team: 
    - If the tournament is a uni marked tournament & all players are not from the same uni (compare email address): (All team members must be from the same university to enter this tournament. If for some reason you believe this is a mistake please (link) contact an admin).
    - Otherwise: (Your team has been signed up for this tournament!)
  - [ ] Sign up button should be replaced with a 'This tournament is full.' message if the team limit is reached
- [ ] List of teams signed up or participating (if the tournament has started)
  - [ ] Captains of teams should be able to pull their team our of a tournament by clicking an X next to their team name in the list of teams (as long as the tournament hasn't started)
- [ ] List of casters for this tournament
  - [ ] Some information about how to sign up to cast a tournament should probably go here
- [ ] Tournament structure (think binarybeast)
## Matches (/tournaments/matches/id)

Each match in a tournament should have its own page.
- [ ] Teams participating
- [ ] Date and time
- [ ] Allocated caster
  - [ ] A user who is marked as a caster for a tournament should be able to add themselves to the match here
  - [ ] When a caster is allocated their twitch steam should be embedded onto the match page (maybe under a Stream tab?)
- [ ] Comments through Discourse, a thread for each match (invisible from the topic list, as to not clutter the front page)
# Teams (/teams/name)

Each team should have its own page which contains the following:
- [ ] Title
- [ ] Roster
- [ ] Tournaments currently entered into with one or two upcoming matches
- [ ] Previous entered tournaments and ranking/position
- [ ] Stats section
  - [ ] Most wins against
  - [ ] Most loses against
- [ ] University (if set)

Captains should be able to perform extra options:
- [ ] Add member to team
  - [ ] This sends a notification/prompt to the user asking if they wish to be in the team, the accept button should be shown on the teams page
  - [ ] Respond to the captain telling them them an invite has been sent and that the user can visit this page to accept the invite
- [ ] Remove member from team (X next to member names)
- [ ] Assign captain to team member (some sort of icon representing 'captainize', should have a confirm dialog)
- [ ] Disband team
  - [ ] Adds a notice to the page 'This team has been disbanded.'
  - [ ] The captain/user who disbanded should be able to reform the team
## Create Team (/teams/new)

Anyone should be able to create a team. They will automatically become the captain on creation. Fields that a team can set (\* for required):
- [ ] Title *
- [ ] Website
- [ ] University
# Admin Actions (/admin)

Various actions that admins can perform - mods can only perform actions marked with a +.

**Tournaments**
- [ ] Create
  - [ ] See fields in tournaments section
- [ ] Suspend/disqualify team (shows on team page) +
- [ ] Edit team positions in tournaments (binarybeast)
- [ ] Cancel
  - [ ] Enter a message which is displayed on the tournaments page
- [ ] Edit match times (should notify teams and caster and add a comment to the match page/thread)

**Casters**

Should be able to click an add button in the casters box on a tournament page in order to add a user to it.
- [ ] Mark a user as a caster for a specific tournament +
  - [ ] Remove a caster from a tournament +
- [ ] Remove comments/feedback from caster pages

**Users**
- [ ] Email users
  - [ ] All
  - [ ] Participating in specific tournament (as a player or caster or admin)
- [ ] Suspend user account for any length of time (seconds - 0 would be infinite) (shows on user page)
