### ISSUE TITLE
Initial Discourse Features

### ISSUE THREAD

**Issue by didehvar** [didehvar/monarchy-node#2]
# Miscellaneous
- [ ] Steam sign up/log in
# User Fields
- [ ] Steam id user profile field
- [ ] University email user field
  - [ ] Should validate @ac.uk
